# Generated by Django 3.2.9 on 2021-11-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pincode', models.IntegerField()),
                ('Status', models.BooleanField()),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AddPage.users')),
            ],
        ),
    ]
