# Generated by Django 3.2.9 on 2021-11-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Status',
            field=models.IntegerField(),
        ),
    ]
